### ISSUE TITLE
Issues Recreating Functions

### ISSUE THREAD

**Issue by abresler** [gluc/useR15#1]
Thanks for the great package and tutorial!  Trying to work through and in the examples for example:

```
 pfo$Get(function(x) x$Weight / x$parent$Weight, traversal = "post-order", assign = "WoP")
```

This spits out an error 

```
Error in attribute(node, ...) : unused argument (assign = "WoP")
```

Same is true for

```
pfo$Get(attribute = Aggregate, 
        function(x) x$Weight * x$Duration / x$parent$Weight, 
        fun = function(x) sum(x, na.rm = TRUE),
        traversal = "post-order",
        assign = "Duration")
```

**Comment by abresler** [comment]
Saw the syntax changes, this works once updated in the useR code

```
pfo$Do(
    function(x) x$WoP <- x$Weight / x$parent$Weight, traversal = "post-order"
    )
```

**Comment by gluc** [comment]
Yes, thanks for trying out. Unfortunately, I didn't have time to maintain this package and of course I should have mentioned that. Apologies!
I did add a few demoes to the package, though, and planning to migrate some of the stuff in here. See  https://github.com/gluc/data.tree/tree/master/demo
